# Finde jüngsten Run-Ordner OHNE run_dir zu evaluieren (vermeidet Rekursion).
- name: Determine latest run directory under results/
  ansible.builtin.set_fact:
    rd: "{{ workdir }}/results/{{ lookup('pipe', 'ls -1td ' ~ workdir ~ '/results/*/ | head -n1 | xargs basename') | trim }}"

- name: Ensure results dir exists
  ansible.builtin.file:
    path: "{{ rd }}"
    state: directory

- name: Dump docker logs per node
  loop: "{{ range(1, node_count + 1) | list }}"
  loop_control: { loop_var: i }
  ansible.builtin.shell: |
    docker logs node{{ '%02d'|format(i) }} > "{{ rd }}/node{{ '%02d'|format(i) }}.log" 2>&1
  changed_when: true

- name: Snapshot chain tips
  ansible.builtin.shell: |
    docker exec node01 bitcoin-cli -regtest getchaintips > "{{ rd }}/chaintips.json"
  changed_when: true

- name: Snapshot mempool info
  ansible.builtin.shell: |
    docker exec node01 bitcoin-cli -regtest getmempoolinfo > "{{ rd }}/mempool.json"
  changed_when: true

# Falls txlog im allgemeinen results liegt, verlinke ihn in diesen Run
- name: Copy txlog from Docker volume to run directory
  ansible.builtin.shell: |
    # Copy txlog.csv from btcnet_txlogs named volume if present
    if docker volume inspect btcnet_txlogs >/dev/null 2>&1; then \
      docker run --rm -v btcnet_txlogs:/v -v {{ rd }}:/out alpine:3.19 sh -lc "if [ -f /v/txlog.csv ]; then cp -f /v/txlog.csv /out/txlog.csv; fi"; \
    fi
  changed_when: false

- name: Run RPC-based confirmation collector
  ansible.builtin.shell: |
    python3 files/confirmation_collector.py --rpc http://{{ rpc_user }}:{{ rpc_pass }}@127.0.0.1:20443 \
      --txlog "{{ rd }}/txlog.csv" --out "{{ rd }}/confirmations.csv" --start-height 0
  args:
    chdir: "{{ workdir }}"
  changed_when: false
