version: "3.9"
services:
    node01:
    image: ruimarinho/bitcoin-core:27.0
    container_name: node01
    command:
      - "-regtest=1"
      - "-printtoconsole=1"
      - "-server=1"
      - "-txindex=1"
      - "-rpcuser=user"
      - "-rpcpassword=pass"
      - "-zmqpubhashblock=tcp://0.0.0.0:28332"
      - "-zmqpubhashtx=tcp://0.0.0.0:28333"
      - "-conf=/bitcoin/.bitcoin/bitcoin.conf"
    volumes:
      - ./data/node01:/bitcoin/.bitcoin
    networks: [ btcnet ]
        ports:
      - "28332:28332"   # ZMQ block
      - "28333:28333"   # ZMQ tx
      - "18443:18443"   # RPC regtest
        node02:
    image: ruimarinho/bitcoin-core:27.0
    container_name: node02
    command:
      - "-regtest=1"
      - "-printtoconsole=1"
      - "-server=1"
      - "-txindex=1"
      - "-rpcuser=user"
      - "-rpcpassword=pass"
      - "-zmqpubhashblock=tcp://0.0.0.0:28332"
      - "-zmqpubhashtx=tcp://0.0.0.0:28333"
      - "-conf=/bitcoin/.bitcoin/bitcoin.conf"
    volumes:
      - ./data/node02:/bitcoin/.bitcoin
    networks: [ btcnet ]
        node03:
    image: ruimarinho/bitcoin-core:27.0
    container_name: node03
    command:
      - "-regtest=1"
      - "-printtoconsole=1"
      - "-server=1"
      - "-txindex=1"
      - "-rpcuser=user"
      - "-rpcpassword=pass"
      - "-zmqpubhashblock=tcp://0.0.0.0:28332"
      - "-zmqpubhashtx=tcp://0.0.0.0:28333"
      - "-conf=/bitcoin/.bitcoin/bitcoin.conf"
    volumes:
      - ./data/node03:/bitcoin/.bitcoin
    networks: [ btcnet ]
        node04:
    image: ruimarinho/bitcoin-core:27.0
    container_name: node04
    command:
      - "-regtest=1"
      - "-printtoconsole=1"
      - "-server=1"
      - "-txindex=1"
      - "-rpcuser=user"
      - "-rpcpassword=pass"
      - "-zmqpubhashblock=tcp://0.0.0.0:28332"
      - "-zmqpubhashtx=tcp://0.0.0.0:28333"
      - "-conf=/bitcoin/.bitcoin/bitcoin.conf"
    volumes:
      - ./data/node04:/bitcoin/.bitcoin
    networks: [ btcnet ]
        node05:
    image: ruimarinho/bitcoin-core:27.0
    container_name: node05
    command:
      - "-regtest=1"
      - "-printtoconsole=1"
      - "-server=1"
      - "-txindex=1"
      - "-rpcuser=user"
      - "-rpcpassword=pass"
      - "-zmqpubhashblock=tcp://0.0.0.0:28332"
      - "-zmqpubhashtx=tcp://0.0.0.0:28333"
      - "-conf=/bitcoin/.bitcoin/bitcoin.conf"
    volumes:
      - ./data/node05:/bitcoin/.bitcoin
    networks: [ btcnet ]
        node06:
    image: ruimarinho/bitcoin-core:27.0
    container_name: node06
    command:
      - "-regtest=1"
      - "-printtoconsole=1"
      - "-server=1"
      - "-txindex=1"
      - "-rpcuser=user"
      - "-rpcpassword=pass"
      - "-zmqpubhashblock=tcp://0.0.0.0:28332"
      - "-zmqpubhashtx=tcp://0.0.0.0:28333"
      - "-conf=/bitcoin/.bitcoin/bitcoin.conf"
    volumes:
      - ./data/node06:/bitcoin/.bitcoin
    networks: [ btcnet ]
        node07:
    image: ruimarinho/bitcoin-core:27.0
    container_name: node07
    command:
      - "-regtest=1"
      - "-printtoconsole=1"
      - "-server=1"
      - "-txindex=1"
      - "-rpcuser=user"
      - "-rpcpassword=pass"
      - "-zmqpubhashblock=tcp://0.0.0.0:28332"
      - "-zmqpubhashtx=tcp://0.0.0.0:28333"
      - "-conf=/bitcoin/.bitcoin/bitcoin.conf"
    volumes:
      - ./data/node07:/bitcoin/.bitcoin
    networks: [ btcnet ]
        node08:
    image: ruimarinho/bitcoin-core:27.0
    container_name: node08
    command:
      - "-regtest=1"
      - "-printtoconsole=1"
      - "-server=1"
      - "-txindex=1"
      - "-rpcuser=user"
      - "-rpcpassword=pass"
      - "-zmqpubhashblock=tcp://0.0.0.0:28332"
      - "-zmqpubhashtx=tcp://0.0.0.0:28333"
      - "-conf=/bitcoin/.bitcoin/bitcoin.conf"
    volumes:
      - ./data/node08:/bitcoin/.bitcoin
    networks: [ btcnet ]
      
  txgen:
    image: python:3.11-slim
    container_name: txgen
    volumes:
      - ./files/txgen.py:/app/txgen.py:ro
      - ./results:/results
    command: ["python","/app/txgen.py","--rate","10","--rpc","http://user:pass@node01:18443","--log","/results/txlog.csv"]
    networks: [ btcnet ]

networks:
  btcnet:
    driver: bridge
